-- 10. NOTIFICATIONS
INSERT INTO public.notifications (id, user_id, type, is_read, title, created_at) VALUES (gen_random_uuid(), '8fb7f5ae-b1d5-4ee7-8652-b757393173a5', 'follow', false, 'James Carter started following you', now() - interval '1 hours') ON CONFLICT DO NOTHING;
INSERT INTO public.notifications (id, user_id, type, is_read, title, created_at) VALUES (gen_random_uuid(), '84ad35bc-5be1-42b1-947a-e073538fd82d', 'follow', false, 'Sophia Lee started following you', now() - interval '1 hours') ON CONFLICT DO NOTHING;
INSERT INTO public.notifications (id, user_id, type, is_read, title, created_at) VALUES (gen_random_uuid(), '29209b5b-6a45-4650-aac7-50d6e2566c5e', 'follow', false, 'Liam Patel started following you', now() - interval '1 hours') ON CONFLICT DO NOTHING;
INSERT INTO public.notifications (id, user_id, type, is_read, title, created_at) VALUES (gen_random_uuid(), '6b64a534-b8cb-485f-8a72-10bd3f876fff', 'follow', false, 'Olivia Garcia started following you', now() - interval '1 hours') ON CONFLICT DO NOTHING;
INSERT INTO public.notifications (id, user_id, type, is_read, title, created_at) VALUES (gen_random_uuid(), '48fd3313-058e-44bf-96e0-a0145a35d943', 'follow', false, 'Noah Smith started following you', now() - interval '1 hours') ON CONFLICT DO NOTHING;
INSERT INTO public.notifications (id, user_id, type, is_read, title, created_at) VALUES (gen_random_uuid(), '5a9bb5f0-0272-4f5e-83c0-79537c0c3087', 'follow', false, 'Ava Johnson started following you', now() - interval '1 hours') ON CONFLICT DO NOTHING;
INSERT INTO public.notifications (id, user_id, type, is_read, title, created_at) VALUES (gen_random_uuid(), '99ac3c33-a767-4e31-a51b-73909e9f8289', 'follow', false, 'William Brown started following you', now() - interval '1 hours') ON CONFLICT DO NOTHING;
INSERT INTO public.notifications (id, user_id, type, is_read, title, created_at) VALUES (gen_random_uuid(), '37a00b47-65e7-4b86-af53-fbf5a9e12eae', 'follow', false, 'Isabella Davis started following you', now() - interval '1 hours') ON CONFLICT DO NOTHING;
INSERT INTO public.notifications (id, user_id, type, is_read, title, created_at) VALUES (gen_random_uuid(), '47307a70-b9c7-41d6-87bb-f9b0d4fc957b', 'follow', false, 'Lucas Miller started following you', now() - interval '1 hours') ON CONFLICT DO NOTHING;
INSERT INTO public.notifications (id, user_id, type, is_read, title, created_at) VALUES (gen_random_uuid(), 'b1c1745b-5077-4c08-b014-8b782c22836f', 'follow', false, 'Mia Wilson started following you', now() - interval '1 hours') ON CONFLICT DO NOTHING;
INSERT INTO public.notifications (id, user_id, type, is_read, title, created_at) VALUES (gen_random_uuid(), 'a0983f86-4812-47d2-992b-052e6af693c4', 'follow', false, 'Ethan Taylor started following you', now() - interval '1 hours') ON CONFLICT DO NOTHING;
INSERT INTO public.notifications (id, user_id, type, is_read, title, created_at) VALUES (gen_random_uuid(), '92591183-d56e-425c-8142-a260a541ecbe', 'follow', false, 'Emma Wilson started following you', now() - interval '1 hours') ON CONFLICT DO NOTHING;
